apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  name
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          readOnly: true
          name: nginx-html        
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf    
      volumes:
      - name: nginx-html
        configMap:
          name: nginx
          items:
            - key: index.html
              path: index.html
      - name: nginx-conf
        configMap:
          name: nginx
          items:
            - key: default.conf
              path: default.conf